# Generated by Django 5.1.6 on 2025-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_remove_profile_description_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
    ]
