# Generated by Django 5.1.6 on 2025-03-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
