# Generated by Django 5.1.6 on 2025-03-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_message_is_read_message_read_at_message_read_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
