# Generated by Django 5.1.6 on 2025-03-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
